simonfuhrmann/mve

apps/umve/glwidget.cc, apps/umve/glwidget.h
This fixes performance problems under recent Qt5-Linux-combinations (for example Ubuntu 14.10). By using a QTimer with a timeout of 0 in single shot mode, all mouse and keyboard events are processed before repaint() is called. [http://qt-project.org/doc/qt-4.8/qtimer.html#details] Thus the scene inspect is interactive again. The window resizing is still a bit sluggish.
=> UMVE: Trigger a repaint only if all window system events have been processed.

apps/sfmrecon/sfmrecon.cc, libs/sfm/bundler_incremental.cc, libs/sfm/bundler_incremental.h
does not actually change current behavior of sfmrecon
=> SFM: add minimal number of valid cameras to track triangulation

Makefile.inc, apps/umve/umve.pro
Qmake otherwise compiles and links against old/outdated c++ libs on OSX.
With this change maxosx-version-min is also no longer necessary in the
MVE Makefile.inc.
=> UMVE: Change MACOSX_DEPLOYMENT_TARGET for qmake

apps/umve/scene_addins/addin_state.cc
This resolves #158.
If new shader programs are created when ```load_shaders()``` is called instead of re-using the old ones, some parts of the rendering are still using the old programs. This results in an inconsistent OpenGL state as the old programs might not be bound any more.
=> UMVE: Fixed bug when reloading shaders

libs/sfm/ba_linear_solver.cc, libs/sfm/ba_linear_solver.h, tests/sfm/gtest_ba_conjugate_gradient.cc
This is useful for 'structure only' or 'motion only' problems
in BA, where the approximate Hessian has a block diagonal
structure and can be inverted directly.
=> SFM: BA add non-Schur solver for linear step

libs/sfm/ba_linear_solver.cc, libs/sfm/ba_sparse_matrix.h, tests/sfm/gtest_ba_sparse_matrix.cc
Using this we no longer need to compute the transpose of the large point
jacobian during the linear LM step.
=> SFM: Add transposed_multiply to sparse matrix

libs/fssr/basis_function.h
Fixes `redefinition of default argument`, default arg is already defined in declaration on line 57.
```
In file included from basis_function.cc:16:
../../libs/fssr/basis_function.h:136:25: error: redefinition of default argument
math::Vector<T, 3>* deriv = nullptr)
^       ~~~~~~~
../../libs/fssr/basis_function.h:58:25: note: previous definition is here
math::Vector<T, 3>* deriv = nullptr);
^       ~~~~~~~
1 error generated.
make[2]: *** [basis_function.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from iso_octree.cc:22:
../../libs/fssr/basis_function.h:136:25: error: redefinition of default argument
math::Vector<T, 3>* deriv = nullptr)
^       ~~~~~~~
../../libs/fssr/basis_function.h:58:25: note: previous definition is here
math::Vector<T, 3>* deriv = nullptr); …
```
=> FSSR: Fix redefinition of default argument

libs/fssr/hermite.cc
std::min and std::max are declared in algorithm.
=> FSSR: Include missing algorithm header

libs/mve/image_io.cc, libs/util/aligned_allocator.h, libs/util/system.cc
- binary mode for MVEI files
- Use aligned_malloc with MinGW
- backtrace not available with MinGW
=> Small changes for MinGW compilation

apps/umve/scene_addins/addin_rephotographer.cc
The ```GL_PACK_ALIGNMENT``` defaults to 4 (word-alignment) instead of 1 (byte-alignment). Thus ```glReadPixels``` requires every row of the ```mve::ByteImage``` to be word-aligned. This is not the case if the width is not a multiple of 4. This fixes a segmentation fault in combination with the current NVIDIA OpenGL implementation.
=> UMVE: Fix memory alignment issue in rephotographer addin

apps/sfmrecon/sfmrecon.cc, libs/sfm/bundler_matching.cc, libs/sfm/bundler_matching.h, libs/sfm/exhaustive_matching.cc, libs/sfm/exhaustive_matching.h, libs/sfm/feature_set.cc, libs/sfm/feature_set.h, libs/sfm/matching.h, libs/sfm/matching_base.h
- Move matching code from `FeatureSet` into its own class(es)
- Introduce `MatchingBase` class which consists of data structures (`Options`, `Result`), helper methods and an interface which are common to different matchers.
- Implement `ExhaustiveMatching` as the first matcher
- Add a pointer to `MatchingBase` in `sfm::bundler::Matching` to support different matchers in the future
=> Refactor matching code

apps/sfmrecon/sfmrecon.cc, libs/math/matrix.h, libs/math/vector.h, libs/sfm/bundler_matching.cc, libs/sfm/bundler_matching.h, libs/sfm/cascade_hashing.cc, libs/sfm/cascade_hashing.h, libs/sfm/exhaustive_matching.cc, libs/sfm/exhaustive_matching.h, libs/sfm/matching.h, libs/sfm/matching_base.h, libs/sfm/nearest_neighbor.h, tests/sfm/gtest_nearest_neighbor.cc
Using cascade hashing for feature matching trades a slight drop in matching
accuracy for a speed-up of an order of magnitude
Speed-up over bruteforce matching on the citywall-20140923 dataset:
1x Intel Core i7-3930K   : ~20.6x
2x Intel Xeon E5-2687W v3: ~18.1x
=> Implement feature matching with cascade hashing

libs/sfm/cascade_hashing.h
- popcntintrin.h is not provided by Visual Studio 2015 but nmmintrin.h
includes _mm_popcnt_u64()
=> SFM: Fix compilation of cascade hash matcher on Visual Studio

libs/math/matrix.h, libs/math/vector.h, libs/sfm/cascade_hashing.h, tests/math/gtest_matrix.cc, tests/math/gtest_vector.cc
- Querying the dimension of a vector or the number of rows/columns of a
matrix is now done by accessing (a) static const variable(s) instead of
calling a method.
- The refactoring of the vector class also works around a compiler bug related
to the constexpr keyword in Visual Studio 2015 Update 1.
=> Refactor matrix/vector dimension(s)

libs/fssr/octree.cc, libs/fssr/octree.h
Speed-up over Octree::node_center_and_size() on citywall-20140923 (L2) dataset:
1x Intel Core i7-3930K (6 cores, 12 threads)     : ~1.43x (~7086.1s -> ~4962.4s)
2x Intel Xeon E5-2687W v3 (2x8 cores, 32 threads): ~1.41x (~3099.0s -> ~2197.6s)
Speed-up over Octree::node_center_and_size() on achteck_turm-20130528 (L2) dataset:
1x Intel Core i7-3930K (6 cores, 12 threads)     : ~2.06x (~1452.2s -> ~705.3s)
2x Intel Xeon E5-2687W v3 (2x8 cores, 32 threads): ~1.89x (~ 644.8s -> ~341.7s)
=> FSSR: Compute node center incrementally in Octree::influence_query()

apps/umve/viewinspect/imageoperations.cc
Dropping `const` declaration of settings struct. 
According to C standard, objects need to have a
user-defined constructor if instances are delcared const.
=> Fix Clang compile error

libs/mve/mesh_io_ply.cc
```Writing PLY file (4264985 verts, with normals, 0 faces, with colors)... done.```
vs.
```Writing PLY file (4264985 verts, with normals, 0 faces)... done.```
Zero faces with colors is somewhat irritating, since colors could still be specified in the ply header...
=> MVE: Fix output of ply writer for point clouds

libs/mve/image_io.cc
- avoids loading image content of wrong type
- loads header twice for correct type
=> Add loading of mvei images to load_image - fail fast version

libs/sfm/_test_matching.cc, libs/sfm/cascade_hashing.cc, libs/sfm/exhaustive_matching.cc, libs/sfm/matching.cc, libs/sfm/matching.h
Further these commits:
- eliminate code duplication (`Matching::combine_results`)
- fix an uninitialized value bug (`sfm::Matching::Options::distance_threshold`)
- allow the inspection of  discretized matching results (which were found to be quite different)
=> SFM: Add surf features to matching test app

libs/sfm/bundler_init_pair.cc
The amount of memory required for the least squares fundamental estimation increases quad radically with the number of matches #264. Limiting the number of matches should result in a significant reduction in memory usage for scenes with a high amount of pairwise matches and would have little impact on scenes with lower amount of pairwise matches.
The limit of 1000 matches is exemplary and should be discussed.
=> SFM: Limit matches for least squares fundamental estimation #264

apps/sfmrecon/sfmrecon.cc, libs/sfm/bundler_init_pair.cc
Add an additional check to the initial pair selection to test if two-view triangulation works for a significant amount of matches.
- This fixes many failures that usually occur when the two-view geometry from the initial pair selection is not optimal and a continued bundling is not possible.  
- Due to this we can also relax the homography test a little bit; which helps significantly for urban scenes where large homographies are very common but it is still possible to find an initial pair. 
We already tested this internally in the context of CR-PLAY.
=> SFM: Fix initial pair failure when triangulation fails

apps/umve/viewinspect/tonemapping.cc
The image range of a float image may exceed the range of float causing a segfault.
This patch skips the creation of the histogram.
Computing image range and bin in double precision would be the other possibility.
=> UMVE: Skip histogram creation if image range exceeds float max

libs/math/line.h, libs/math/plane.h
Plane invert did not invert the plane, like the name suggests, but returned an inverted plane.
=> MATH: Fix unexpected behaviour with plane inversion

apps/umve/scene_addins/addin_rephotographer.cc, libs/mve/camera.cc, libs/mve/camera.h
I tried to put these functions into `math/matrix_tools.h` but the creation of the projection matrix requires a lot of information from `mve::CameraInfo` and relies on our camera convention so it felt more natural to put it into `mve::CameraInfo` directly.
=> Extract gl matrix creation

apps/meshalign/stanford_alignment.cc, libs/math/quaternion.h, libs/ogl/camera_trackball.cc, tests/math/gtest_quaternion.cc
The rotation matrix is written out as column major, resulting in transposed rotations.
=> Fix quaternion to rotation matrix conversion (wrong matrix convention)

dist/snap/snapcraft.yaml
This allows the user to connect the "removable-media" interface and
grant mve access to the files located in their removable media.
=> Snap: add removable-media interface

apps/umve/scene_addins/addin_selection.cc
To give a little context: I encountered a crash (segfault) in UMVE when selecting sfm points in a scene where some of the view directories were removed.
=> UMVE: only select existing views

apps/umve/glwidget.cc, apps/umve/glwidget.h, apps/umve/scene_inspect/scene_inspect.cc, apps/umve/umve.cc, apps/umve/viewinspect/viewinspect.cc
- See [Qt Blog](http://blog.qt.io/blog/2014/09/10/qt-weekly-19-qopenglwidget/)
- Also fixes crashes on OSX
=> UMVE: Change GL widget to newer QOpenGLWidget

libs/sfm/bundler_incremental.cc, libs/sfm/triangulate.cc, libs/sfm/triangulate.h
If a track can be triangulated with a subset of cameras
the other cameras, causing large errors, are now separated
from the track and a new track is generated. This helps if
false matches connect two otherwise fine tracks.
=> SFM: Find outliers during track triangulation

apps/dmrecon/dmrecon.cc, apps/scene2pset/scene2pset.cc, apps/sceneupgrade/sceneupgrade.cc, libs/mve/scene.h, libs/mve/view.h, tests/mve/gtest_view.cc
This is a rework of PR #337.
Refactor of Scene and View class code to make it easier to read and maintain:
- Replaced index based loops, with foreach loops where possible
- Removed raw constructors from public API
- Removed commented out code
- Removed unused control flow parameters of internal functions
- Replaced pointer parameters by reference parameters where nullptr would be illegal as argument.
No functional changes.
=> Removal of raw Scene and View constructors from public API

apps/umve/mainwindow.cc
Parameterless version of Scene::create() was removed by #338.
=> Fix a bug with missing Scene::create()

apps/umve/scene_addins/addin_base.h
Fix building error on archlinux with gcc7.
Erro message:
>g++ -c -pipe -fPIC -fopenmp -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -std=gnu++11 -D_REENTRANT -Wall -W -fPIC -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../libs -isystem /usr/include/libdrm -isystem /usr/include/qt -isystem /usr/include/qt/QtOpenGL -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -Ibuild -I/usr/lib/qt/mkspecs/linux-g++ -o build/addin_frusta_base.o scene_addins/addin_frusta_base.cc
In file included from ./scene_addins/addin_base.h:17:0,
from ./scene_addins/addin_aabb_creator.h:16,
from scene_addins/addin_aabb_creator.cc:15:
../../libs/ogl/context.h: In member function ‘void …
=> fix linux compilation error

libs/sfm/Makefile
Without -msse4.2 gcc7 complains about `target specific option mismatch `
=> Add essential -mxxx build flag for successfull gcc6/linux compilation.

libs/ogl/shader_program.cc, libs/ogl/shader_program.h
Similar to the shader compilation error reporting, we should also show the errors when linking shaders. This PR implements this by retrieving the program info log in case the linking failed after the ``glLinkProgram`` call.
=> OGL: report program linking errors

libs/util/file_system.cc, libs/util/file_system.h, tests/mve/gtest_scene.cc
My current work on mve requires some extension to mve::Scene and without a good set of unit test available it is pretty hard to verify if anything broke. The unit test are set up to read like a specification and to provide clear messages on test failure. Please let me know if there are any errors in this specification.
This PR adds a function to remove directories, so that the unit tests can properly clean up after themselves. I did not test this function on windows.
At the moment two tests fail, because the bundles do not seem to save the pixel aspect ratio of cameras properly. They always reset to 1.0 on reload. Is this a bug or expected behavior?
```
...
[----------] Global test environment tear-down
[==========] 106 tests from 13 test cases ran. (265 ms total)
[  PASSED  ] 104 tests. …
```
=> Unit tests for mve::Scene.

libs/sfm/bundler_incremental.cc
The image undistortion expects distortion parameters in original camera coordinates and handles the focal length itself. So this conversion here is actually a bug, and we create wrong undistorted images later on.
I don't remember why we did this, was there ever a reason to do this multiplication?
=> SFM: Fix conversion of radial distortion in bundler

apps/sfmrecon/sfmrecon.cc, libs/sfm/bundler_common.cc, libs/sfm/bundler_common.h, libs/sfm/bundler_incremental.cc, libs/sfm/bundler_incremental.h
- Add an undistortion function for image features and use corrected features for track triangulation.
- If possible restore initial outlier tracks for viewports after intrinsics have been optimized.
=> SFM: Always consider radial distortion

README.md
TU Darmstadt apparently completely shut down HTTP
=> README: Change GCC website link to HTTPS

apps/makescene/makescene.cc, libs/mve/view.cc
Implementation for fixed intrinsics in makescene.
- makescene has a new parameter effective when importing images (with -i): "--init-intrinsics f,k1,k2,ppx,ppy,pa". For instance "--init-intrinsics 0.8,0.1,-0.1,0.5,0.5,1.0". This will simply fill up the view's meta.ini
-  load/store "radial_distortion" parameter in view's meta.ini
=> Allow to initialize camera intrinsics in makescene

libs/sfm/bundler_common.h, libs/sfm/bundler_features.cc, libs/sfm/bundler_intrinsics.cc, libs/sfm/camera_pose.h, libs/sfm/feature_set.cc, libs/sfm/feature_set.h
The second PR related to integrating fixed intrinsics in BA.
- Principal point is used in feature normalization (defaults to 0.5)
- Radial distortion is used in BA, either as a starting point or as a fixed parameter (defaults to 0.0)
=> Use principal point in feature normalization and radial distortion in BA

Makefile.inc
Hello there :hand:
Currently the default build settings will force MVE to be compiled using instruction sets that sometimes are not available to the CPU. Unless I've missed something, wouldn't specifying `march=native` take care of selecting the best available set of instructions for the user?
https://stackoverflow.com/questions/10686638/whats-the-differrence-among-cflgs-sse-options-of-msse-msse2-mssse3-msse4
https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
I thought I'd open a PR, but if I've overlooked something please feel free to close it.
Thanks!
=> Allow MVE to run on older hardware

apps/Makefile
By building the projekt with `make`, `prebundle` is not built at the moment. Is this intended?
=> APPS: also build, clean and link apps/prebundle/prebundle

libs/util/file_system.cc, libs/util/system.cc, libs/util/system.h
Hello :hand: 
This is a small set of changes that is required to compile mve under Cygwin.
Thought I'd contribute the changes for others to use :+1:
=> Added directives to compile under Cygwin

apps/makescene/makescene.cc
Hello :hand: 
This is a minor fix for `makescene` for cases when a Bundler dataset has spaces in the filenames of images (for example, `DJI 0018.JPG`). The root cause is that >> stops at the first white space or new line, whichever comes first. `makescene` then fails with:
```
Creating output directories...
Saving bundle file...
Writing bundle (4 cameras, xxx features): /path/to/output/synth_0.out...
Processing view view_0000.mve...
Error loading: /path/to/images/DJI
```
This code change simply uses std::getline, which reads the entire line, until it finds a new line character, skips the new line character and continues with the next line. https://en.cppreference.com/w/cpp/string/basic_string/getline
Test case to reproduce: [testcase.zip](https://github.com/simonfuhrmann/mve/files/2920462/ …
=> Fixed white space noah bundler import bug

apps/makescene/makescene.cc
Hello :hand:
Sometimes when importing a scene via `makescene` an image might be corrupted. Instead of failing the process, it could be useful to allow the program to continue processing the rest of the scene while informing the user that a particular view could not be created.
This seems like it was the original intention per the comment to "handle exceptions while loading images".
Alternatively we could add a flag that specifies whether `makescene` should fail on import (the current behavior) or be more tolerant (the proposed change). Happy to make changes if needed / requested. :clinking_glasses:
=> Skip invalid views

Dockerfile, libs/util/system.cc
The current compatibility checks in the libs/util/system.cc
check for the __GNUC__ flag when deciding whether to include
the execinfo.h header and backtrace functionalityt. The
__GNUC__ flag returns true for distros that do not inlude glibc
which will cause compilation issues for musl libc.
The check now looks for __GLIBC__ and will properly exclude the
functionality from distros using a different libc implementation.
Also a Dockerfile is included which can be used to validate builds
on musl based distros such as Alpine.
=> Check for GLIBC rather than GNUC for compatibility

libs/math/vector.h
This PR defines vector types of unsigned short (which are missing).
To provide some context on why I'm suggesting to add these, I'm working on expanding mvs-texturing to support 16bit textures (https://github.com/pierotofy/mvs-texturing/tree/depth) (which require this data type for certain inputs). This vector type is not directly used by MVE apps, but might be useful for others looking to use MVE as a library.
=> Added unsigned short vector types

libs/util/file_system.cc
from documentation for function `readdir`:
```
Currently, only some filesystems (among them: Btrfs, ext2, ext3,
and ext4) have full support for returning the file type in d_type.
All applications must properly handle a return DT_UNKNOWN
```
To avoid problems with not supported file system, `is_dir` flag additionally  computed via function `stat`, which don't have same constraints.
In my case, `DT_UNKNOWN` was given from `readdir`, if sub-folder is mounted via `sshfs`.
=> fix not supported file system cases

apps/makescene/makescene.cc, libs/mve/bundle_io.cc, libs/mve/bundle_io.h
This PR allows to import Colmap's SfM model formats (`.bin` as well as `.txt` files). 
Let us assume the following folder structure:
```
<Colmap workspace> 
<images>
<sparse model>
cameras.txt / cameras.bin
images.txt / images.bin 
points3D.txt / points3D.bin
```
The importer looks on the same level than the `<sparse model>` for the  `<image folder>` with the corresponding images.
Also, the importer searches first for the `.txt` files in the `<sparse model>` folder. 
In order to validate the imported results, I performed a reconstruction with Colmap and exported the results as `.NVM` file as well as Colmap's standard model folders (.txt and .bin). Then, I compared the values in the `Bundle::Ptr` returned by `load_nvm_bundle` and `load_colmap_bundle`. I did not add the testing code, since …
=> Support for importing Colmap SfM models

apps/makescene/makescene.cc, libs/mve/bundle_io.cc
Fix Colmap importer intrinsic conversion and remove redundant depth map conversion code
=> Fix importer intrinsics

.travis.yml, tests/Makefile
I've noticed that [recent travis builds](https://travis-ci.org/github/simonfuhrmann/mve/builds) failed for a reason that has nothing to do with the code.
After some searching, I've found that [cmake should be run in googletest's home directory, not googletest/googletest](https://github.com/google/googletest/issues/2882#issuecomment-753471115).
So this PR revise `GTEST_PATH` and update the include directory in `tests/Makefile` accordingly.
You can see that these changes make travis build successfully: https://travis-ci.org/github/keineahnung2345/mve/jobs/757523169.
=> Fix travis build issue

libs/sfm/nearest_neighbor.cc
Fixes compilation for CPUs that don't support SSE2/3.
Fixes #572
=> SFM: Guard inclusion of SSE headers

libs/mve/image_io.cc
This MR contains a minor improvement to a vsnprintf() call which was introduced in a recent commit.
=> MVE: Don't hardcode vsnprintf() destination buffer size

.github/workflows/main.yml
Hi,
this PR updates the macOS CI by removing the macOS 12 CI pipeline because the runner image has been deprecated since 3rd December 2024 and adding a macOS 15 CI pipeline.
=> Update macOS CI

libs/mve/mesh_io.cc, libs/mve/mesh_io_glb.cc, libs/mve/mesh_io_glb.h
Hi,
this PR implements a Binary glTF 2.0 (aka GLB) exporter. The code was implemented according to the glTF 2.0 spec available at:
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html
The implementation was tested by validating the resulting GLB with the official glTF Validator:
https://github.khronos.org/glTF-Validator/
Fixes #571
=> MVE: Implement Binary glTF 2.0 mesh export
