simonfuhrmann/mve

- libs/mve/image_io.cc
[MVE] added missing define checks in image_io
> [MVE] added missing define checks in image_io

- libs/sfm/camera_database.cc
> SFM: correct and extend camera database

- apps/umve/clickimage.h
- apps/umve/viewinspect/scrollimage.cc
- apps/umve/viewinspect/scrollimage.h
- apps/umve/viewinspect/viewinspect.cc
This is an enhancement that improves the handling of image viewing in UMVE (#159)
* Mouse navigation (with left mouse button)
* Zooming with mouse wheel (while keeping the location under the cursor)
* Disable checkability of zoom to fit button
* Use zoom to fit as default when opening a scene
> UMVE: Improved image viewing

- apps/meshclean/meshclean.cc
This change introduces a new option '-p' to specify a percentile for calculating the threshold used to clean low-conf vertices. It replaces '-t' as the default, but '-t' can still be used so that this change is non-breaking. If both options are given, then '-p' is preferred over '-t'.
Another option would be to only have the '-t' parameter to specify some value and introduce a new flag (--use-percentiles or --use-absolute-threshold) which defines if this threshold is an absolute value or a percentile.
> Add confidence percentile threshold to meshclean

- apps/meshclean/meshclean.cc
> Fix argument parser of meshclean

- libs/sfm/exhaustive_matching.cc
- This got lost in the refactoring of the matching code
> SFM: Parallelize feature processing in exhaustive matcher

- apps/makescene/makescene.cc
FYI, the first approach I tried was to use OpenMP's `ordered` directive but that performed rather poorly with gcc 4.8.2 (only ~20% faster) and gcc 5.1.0 (only ~33% faster) compared to the single threaded version. On Visual Studio 2015 Update 2 the performance of the `ordered` directive was about as fast as the solution with the semaphores. But because I want the same performance on both platforms I chose the solution with the semaphores.
> Parallelize makescene

- libs/sfm/_test_matching.cc
Maybe those testing apps should be included in Travis elsewise they will break whenever somebody refactors something.
> Fix matching test app (only sift)

- apps/makescene/makescene.cc
> APPS: Fix makescene import of 16 bit tiff files

- README.md
Old Nokia link doesn't work anymore.
> DOCS: Update Qt link in README.md

- apps/umve/scene_addins/addin_rephotographer.cc
The current implementation uses the computer vision camera convention (looking into the direction of z) and compensates with flips of y and z in the projection. This results in incorrect normals during shading.
> Fix matrix computation of rephotographer (OpenGL convention)

- libs/sfm/bundler_tracks.cc
I encountered a dataset where the track propagation did not complete after 24 hours. Unifying in the larger of both tracks and effectively reserving the required memory beforehand with insert reduced the runtime to under 15 seconds.
> SFM: Improve worst case runtime of track propagation v2

- apps/sfmrecon/sfmrecon.cc
- libs/math/matrix_tools.h
- libs/math/transform.h
- libs/sfm/ba_types.h
- libs/sfm/bundle_adjustment.cc
- libs/sfm/bundler_common.cc
- libs/sfm/bundler_common.h
- libs/sfm/bundler_incremental.cc
- libs/sfm/bundler_incremental.h
I am happy to rename any of the newly introduced concepts.
Alternatives for survey point: tie point, anchor, ground control point, control point
Alternatives for survey point observation: marker, control feature, annotation
@seepa thanks for your help :-)
> Add survey point support

- apps/umve/mainwindow.cc
> UVME: Load files based on lowercase of extension

- libs/math/matrix_svd.h
- libs/math/transform.h
Resolving threshold discussion of #312
> MATH: Introduce macro for the SVDs default zero threshold

- libs/sfm/ransac_pose_p3p.cc
- libs/sfm/ransac_pose_p3p.h
> SFM: Parallelize ransac 3D pose

- libs/sfm/ba_sparse_matrix.h
> SFM: Paralellize sparse matrix multiplication

- libs/sfm/bundle_adjustment.cc
> SFM: Parallelize jacobian computation

- apps/sfmrecon/sfmrecon.cc
- libs/sfm/bundle_adjustment.cc
- libs/sfm/bundle_adjustment.h
- libs/sfm/bundler_incremental.cc
+ Add new termination condition to BA
+ BA compute exact jacobian entries
+ Apply radial distortion when checking for outlier tracks
+ Update sfmrecon workflow
+ Update sfmrecon parameters for scalability
> IMBA: performance and stability improvements

- libs/math/functions.h
- libs/sfm/cascade_hashing.h
- tests/math/gtest_functions.cc
> SfM: Changed popcount implementation to use std::bitset::count()

- apps/scene2pset/scene2pset.cc
- libs/mve/depthmap.cc
- libs/mve/depthmap.h
I'd be happy to contribute the "output dense correspondence" feature to MVE. Please have a look at this PR.
> Outputting dense 2D<-->3D correspondence data

- libs/sfm/bundler_common.cc
> Fix solve_undistorted_squared_radius stability

- apps/makescene/makescene.cc
Adds support for multi-threaded makescene. It handles photosynth bundle imports by precomputing the camera IDs using a ID --> cameraID dict. Is also declares the num_valid_cams and undist_imported variables as atomic to prevent increment operations from being skipped.
Related to #253
> Parallel makescene

- libs/mve/view.cc
Alternate, better fix than the one proposed in #477.
> Fix race condition

- apps/umve/viewinspect/imageoperations.h
- libs/math/defines.h
- libs/mve/image_io.cc
- libs/util/aligned_allocator.h
This PR fixes some issues I encountered while compiling MVE with VS 2015.3 and running the test suite.
> Fix some Windows/Visual Studio issues

- apps/makescene/makescene.cc
Hello :hand:
This PR proposes a few changes to the `import_bundle_nvm` function of `makescene` so that images with 16bit of depth can be loaded and reconstructed by MVE (via downscaling to 8bit).
If changes are needed, please let me know. :pray:
I can also provide test data/steps if needed.
Thank you!
> Ability to load NVM images with 16bit depth

- libs/mve/image_io.cc
- libs/mve/image_io.h
Hello :hand:
This PR adds support for TIFF files in the `load_file_headers`, which is currently missing.
Hope this is useful for others. :+1:
Please let me know if changes are needed.
> Add support for TIFF files in load_file_headers

- apps/makescene/makescene.cc
- libs/mve/image_io.cc
- libs/mve/image_io.h
Hello :hand:
This PR adds support for importing float TIFF files via makescene. I hope it can be useful to others.
:clinking_glasses:
> Makescene float support

- libs/util/system.h
Adds two utility functions to read little endian binary streams. 
This PR serves as preparation for #509.
> Added reading little endian functions

- apps/makescene/makescene.cc
- libs/mve/bundle_io.cc
- libs/mve/bundle_io.h
> Extension of Colmap Importer

- libs/dmrecon/global_view_selection.cc
Fix  issue: https://github.com/simonfuhrmann/mve/issues/523
> add feature see check
